_wandb:
    value:
        cli_version: 0.23.1
        e:
            q7r2stpr52bkfukcwgob51ep58ase7vu:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 8
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "4294967296"
                codePath: Final/Untitled.ipynb
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "225331298304"
                email: paras.ningune01@gmail.com
                executable: /Library/Frameworks/Python.framework/Versions/3.12/bin/python3.12
                git:
                    commit: e62414f3f92ad72b1c871503339c69b7d2d99f59
                    remote: https://github.com/ParasNingune/Final-Year-Project.git
                host: Parass-MacBook.local
                memory:
                    total: "8589934592"
                os: macOS-26.1-arm64-arm-64bit
                program: Final/Untitled.ipynb
                python: CPython 3.12.3
                root: /Users/parasningune/Desktop/Final-Year-Project/Codebase/best/Final
                startedAt: "2026-01-18T07:23:18.156239Z"
                writerId: q7r2stpr52bkfukcwgob51ep58ase7vu
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 2
                - 3
                - 5
                - 12
                - 49
                - 53
                - 105
            "2":
                - 2
                - 3
                - 5
                - 12
                - 49
                - 53
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.3
            "5": 0.23.1
            "8":
                - 1
            "12": 0.23.1
            "13": darwin-arm64
activation:
    value: relu
batch_size:
    value: 8
conv_layers:
    value: 6
dense_units:
    value:
        - 20
        - 20
epochs:
    value: 50
filters:
    value: 32
input_shape:
    value:
        - 512
        - 512
        - 2
kernel_size:
    value:
        - 3
        - 3
loss:
    value: binary_crossentropy
optimizer:
    value: Adam
pool_size:
    value:
        - 2
        - 2
